name: WakaTime stats update

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # ✅ Time-based metrics and languages
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"

          # ❌ Disable unwanted info
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"  # hides storage, hire status, repo counts
          SHOW_OS: "False"          # hides operating system stats
          SHOW_LOC_CHART: "False"
          SHOW_COMMIT: "True"
          SHOW_UPDATED_DATE: "True"
